{% set name = "jsonpath-ng" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5483f8e9d74c39c9abfab554c070ae783c1c8cbadf5df60d561bc705ac68a07e

build:
  noarch: python
  number: 0
  entry_points:
    - jsonpath.py=jsonpath_ng.bin.jsonpath:entry_point
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ply
    - decorator
    - six

test:
  imports:
    - jsonpath_ng

about:
  home: https://github.com/h2non/jsonpath-ng
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python JSONPath Next-Generation

  description: |
    A final implementation of JSONPath for Python that aims to be standard compliant,
    including arithmetic and binary comparison operators.
  dev_url: https://github.com/h2non/jsonpath-ng

extra:
  recipe-maintainers:
    - shcheklein
    - efiop
